export const skilllist = [
    "Accounting",
    "Payroll",
    "Accounts Payable",
    "Accounts Receivable",
    "Data Entry",
    "Online Research",
    "Order Processing",
    "Project Management",
    "Transcription",
    "Administrative Assistance",
    "Customer Service",
    "Tech Support",
    "A/B Testing",
    "Data Analytics",
    "Bandits",
    "Data Engineering",
    "Data Extraction",
    "Data Processing",
    "Data Visualization",
    "Deep Learning",
    "Machine Learning",
    "NLP",
    "Animation",
    "Art Direction",
    "Audio Editing/Post-Production",
    "Brand Design",
    "Brand Strategy",
    "Creative Direction",
    "Editorial Direction",
    "Graphic Design",
    "Illustration",
    "Video Production",
    "Database Administration",
    "DevOps Engineering",
    "Network Security",
    "Information Architecture",
    "Information Security",
    "Solutions Compliance",
    "Network Administration",
    "Automation QA",
    "Back-End Development",
    "CMS Development",
    "Database Development",
    "Front-End Development",
    "Functional QA",
    "Mobile Design",
    "Scrum Master",
    "User Research",
    "Full Stack Development",
    "UX/UI Design",
    "Web Design",
    "Product Development",
]